### ISSUE TITLE
nuxtjs with electron `loadURL` is slow

### ISSUE THREAD

**Issue by alexchopin** [nuxt-community/electron-template#11]
https://github.com/nuxt/nuxt.js/issues/1635

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt-community/electron-template/issues/c6">#c6</a>)</em></sub></div>

**Comment by detrohutt** [comment]
@alterhu2020 Try the new version of this template using `vue-cli`. If this doesn't solve your issue I can reopen this issue.
