### ISSUE TITLE
Cannot find module 'nuxt'

### ISSUE THREAD

**Issue by lyric-index** [nuxt-community/electron-template#12]
This problem occurs when I try to pack.

![image](https://user-images.githubusercontent.com/23474941/31056084-e0ce8352-a6fe-11e7-8027-54ac03d771fa.png)
- OS Version: Windows_NT ia32 10.0.16294
- Node version: v8.6.0
- NPM version: 5.4.2

Steps to Reproduce:

npm run package:win 
(npm run build && electron-packager ./ nuxt-cli --platform=win32 --arch=x64 --version=1.7.8 --out=./ --overwrite --icon=favicon.ico --ignore=node_modules --prune)

![image](https://user-images.githubusercontent.com/23474941/31056173-3630a5e0-a700-11e7-9b3e-237a77ae8daf.png)

**Comment by lyric-index** [comment]
I have solved it.

**Comment by alexchopin** [comment]
Hi @lyric-index,
Can you explain how you've solved it and close the issue?
Thanks.

**Comment by jeehoonkang** [comment]
I'm experiencing the same symptom.  @lyric-index please share your solution 😃

**Comment by kkcy** [comment]
hey @lyric-li , could you share a little bit more on the solution, facing the same issue with both electron-packager and electron-builder

![capture](https://user-images.githubusercontent.com/9082853/53732269-64f20d00-3eb8-11e9-93ad-8ee2ec38ae21.PNG)

**Comment by kkcy** [comment]
> hey @lyric-li , could you share a little bit more on the solution, facing the same issue with both electron-packager and electron-builder
> 
> ![capture](https://user-images.githubusercontent.com/9082853/53732269-64f20d00-3eb8-11e9-93ad-8ee2ec38ae21.PNG)

sorry. just a silly mistake. nuxt was added as devDependencies instead of dependencies
