### ISSUE TITLE
Axios breaks the loading?

### ISSUE THREAD

**Issue by alexisohayon** [nuxt-community/electron-template#13]
Hi,

Nice package! I'm facing an issue that blocks the loading, apparently caused by the axios package (https://github.com/nuxt-community/axios-module).
I get a "Cannot read property 'env' of undefined" error : 
<img width="1544" alt="capture d ecran 2017-11-17 a 16 23 08" src="https://user-images.githubusercontent.com/781456/32954536-abcc1e92-cbb3-11e7-8d4d-7a2c99bb1139.png">

Any idea how to fix this? :) Thanks!

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt-community/electron-template/issues/c13">#c13</a>)</em></sub></div>

**Comment by yoanmarchal** [comment]
i just deal with this issue with add to nuxt.config.js 
`mode: 'spa'` 
[ex:](https://github.com/nuxt/nuxt.js/blob/dev/examples/spa/nuxt.config.js)

without it, it make my app silent fail

**Comment by detrohutt** [comment]
If this is still an issue with the new version and the workaround above doesn't work, let me know and I'll reopen this issue.

**Comment by ashxdev** [comment]
Hi,
I've the same issue with latest nuxt-edge, nuxt-axios and electron.
Any ideas how to fix this?
